# action.yaml
---
name: 'github-app-installation-auth'
description: 'Authenticate as a github app installation and generate a token'
branding:
  icon: lock
  color: blue
inputs:
  private-key:
    description: 'Github App Private Key'
    required: true
  app-id:
    description: 'Github App ID'
    required: true
outputs:
  github_app_token:
    description: 'Github App Installation Token'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.get-token.outputs.github_app_token }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Fetch the number's square
      id: get-token
      run: |
        GITHUB_APP_TOKEN=$(${{ github.action_path }}/src/github_app_token.py \
          --direct \
          --app-id "${{ inputs.app-id }}" \
          --private-key "${{ inputs.private-key }}"
        )
        echo "github_app_token=$GITHUB_APP_TOKEN" >> $GITHUB_OUTPUT
      shell: bash
